### ISSUE TITLE
Updater le glossaire

### ISSUE THREAD

**Issue by LipoBruh** [protolabo/calque#10]
https://docs.google.com/document/d/1g8vHeiVHomiLQ1JzeRc9UT3FZ8ufI8jstZl4XTcKcPk/edit#heading=h.jrbzp5pe16p1

**Comment by YkseBay** [comment]
Ajouté:
- Edge
- Edge double
- Horaire
- Ligne
- Attribut de edge

**Comment by YkseBay** [comment]
et Noeud

**Comment by YkseBay** [comment]
ajouté:
- Service
- Catégorie
- Image de fond/Background
- Diaporama
- Logo
- Nom complet
- Label
- Heure d'ouverture

**Comment by LipoBruh** [comment]
Voir doc : https://docs.google.com/document/d/1g8vHeiVHomiLQ1JzeRc9UT3FZ8ufI8jstZl4XTcKcPk/edit
