### ISSUE TITLE
figma prototype

### ISSUE THREAD

**Issue by divcamillediv** [protolabo/calque#13]
- how would the designer see the screen?
- what does the start menu look like?
- convert what lipo did to figma

**Comment by LipoBruh** [comment]
-Réfléchir aux fonctionnalités existantes : Comment communiquer leur affordance plus clairement
-Penser aux raccourcis 
-Penser à communiquer l'affordance intuitivement
-Penser au layout optimal pour le travail
-Penser à quelles informations masquer vs quelles informations afficher
-Penser au style de l'interface, penser au style des outils
-Penser aux heuristiques
-Évaluer le modèle conceptuel

**Comment by LipoBruh** [comment]
![print](https://github.com/protolabo/calque/assets/132153958/2de008b1-40e1-4ae4-a325-3ca23c35cb9e)
![prototype user](https://github.com/protolabo/calque/assets/132153958/6e80bcd3-5ef9-4687-ad6c-8995c31aaf0f)

Rappel

**Comment by LipoBruh** [comment]
![image](https://github.com/protolabo/calque/assets/132153958/497c4222-6e39-4875-951a-1b50e7c55607)


Progression de l'esthétique

**Comment by LipoBruh** [comment]
Fin de la phase de prototypage
