### ISSUE TITLE
Explore all design patterns

### ISSUE THREAD

**Issue by LipoBruh** [protolabo/calque#9]
https://refactoring.guru/design-patterns

Read

**Comment by LipoBruh** [comment]
https://www.youtube.com/watch?v=QNpwWkdFvgQ&ab_channel=Geekific
https://www.youtube.com/watch?v=tv-_1er1mWI&ab_channel=Fireship
https://www.youtube.com/watch?v=tAuRQs_d9F8&ab_channel=NeetCode
https://www.youtube.com/watch?v=YMAwgRwjEOQ&ab_channel=AlexHyett

**Comment by LipoBruh** [comment]
https://codewithpawan.medium.com/understanding-solid-principles-in-javascript-and-node-js-9abb09760049

**Comment by YkseBay** [comment]
Lu environ la moitié des patterns sur Refactoring Guru, reste l'autre moitié à lire.

**Comment by LipoBruh** [comment]
Member have gained a good grasp of the concepts.
